# Generated by Django 4.2.4 on 2023-08-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Contect_No", models.IntegerField()),
                ("address", models.TextField()),
            ],
            options={
                "ordering": ["User_Name"],
            },
        ),
    ]
